### ISSUE TITLE
set headers in gosf-socketio for jwt

### ISSUE THREAD

**Issue by celevra** [ambelovsky/gosf#7]
Hi,

is there a way to set headers in gosf-socketio for jwt authentification?

regards

Celevra

**Comment by ambelovsky** [comment]
Celevra,

HTTP headers and websockets operate using entirely different protocols. Authenticating with HTTP headers before an upgrade to websockets is not secure.  You must authenticate over websockets to secure websockets, because HTTP can be skipped entirely when making websocket connections.  It is like writing a password prompt in a separate program; I can just minimize it and do whatever I want to do.

Emit your token over a socket connection. Don’t pass it in an HTTP header.

Spend some time with websockets at a low level before jumping into high level frameworks like socket.io and GOSF.  GOSF is very highly opinionated and locks you into a very specific paradigm on the way to micro-service development.  Really, it’s just a fun experiment with websockets for microservice communication.  It’s not the best microservice framework out there.

The final answer to your previous question was not to use the underlying socket-io framework.  You may be missing the point of GOSF.  Please consider micro-service architecture before revisiting GOSF.  Slow down, and take your time learning websockets and socket.io first.

All my best!

Enviado do meu iPhone
